'use client';

import { useFarcasterDetection } from '@/app/hooks/useFarcasterDetection';
import sdk from '@farcaster/miniapp-sdk';

/**
 * 🔮 Farcaster Entanglement Display
 * 
 * Shows entanglement information specifically optimized for Farcaster frames
 * Highlights the collaborative nature of the circular system
 */
export default function FarcasterEntanglementDisplay({ 
  tokenId, 
  ethMferId,
  generator 
}: { 
  tokenId?: number;
  ethMferId?: number;
  generator?: string;
}) {
  const { isFarcaster } = useFarcasterDetection();
  
  // Only show in Farcaster environment
  if (!isFarcaster) return null;
  
  return (
    <div className="farcaster-entanglement">
      <div className="entanglement-header">
        <h3>🔮 Collaborative Entanglement</h3>
        <p>Each mint creates magic for the next person!</p>
      </div>
      
      {tokenId && ethMferId && (
        <div className="entanglement-info">
          <div className="info-row">
            <span className="label">Your Token:</span>
            <span className="value">#{tokenId}</span>
          </div>
          <div className="info-row">
            <span className="label">Entangled with:</span>
            <span className="value">Ethereum Mfer #{ethMferId}</span>
          </div>
          {generator && (
            <div className="info-row">
              <span className="label">Generated by:</span>
              <span className="value">{generator.slice(0,6)}...{generator.slice(-4)}</span>
            </div>
          )}
        </div>
      )}
      
      <div className="entanglement-explanation">
        <h4>How it works:</h4>
        <ul>
          <li>🎁 Your mint generates entanglement data for the next person</li>
          <li>🔄 Token #1000 creates magic for Token #1 (eternal circle)</li>
          <li>🎲 Uses beacon chain entropy for randomness</li>
          <li>🤝 Collaborative gifting between strangers</li>
        </ul>
      </div>
      
      <div className="farcaster-actions">
        <button
          className="share-entanglement"
          onClick={async () => {
            const text = `Just minted Token #${tokenId} entangled with Ethereum Mfer #${ethMferId} on @KinGallery! Each mint creates magic for the next person in an eternal circle. Revolutionary collaborative NFT system on @base`;
            const embedUrl = 'https://kingallery.netlify.app';

            try {
              if (sdk.actions?.composeCast) {
                await sdk.actions.composeCast({
                  text,
                  embeds: [embedUrl],
                });
              } else if (sdk.actions?.openUrl) {
                await sdk.actions.openUrl(
                  `https://warpcast.com/~/compose?text=${encodeURIComponent(text)}&embeds[]=${encodeURIComponent(embedUrl)}`
                );
              } else {
                window.open(
                  `https://warpcast.com/~/compose?text=${encodeURIComponent(text)}&embeds[]=${encodeURIComponent(embedUrl)}`,
                  '_blank'
                );
              }
            } catch (error) {
              console.error('Error sharing entanglement:', error);
            }
          }}
        >
          Share Your Entanglement
        </button>
      </div>
      
      <style jsx>{`
        .farcaster-entanglement {
          background: linear-gradient(135deg, rgba(5,8,10,0.95), rgba(15,25,35,0.95));
          border: 2px solid #00D4FF;
          border-radius: 16px;
          padding: 20px;
          margin: 16px 0;
          color: white;
          font-family: -apple-system, BlinkMacSystemFont, sans-serif;
        }
        
        .entanglement-header h3 {
          margin: 0 0 8px 0;
          color: #00D4FF;
          font-size: 18px;
        }
        
        .entanglement-header p {
          margin: 0 0 16px 0;
          color: #B0C4DE;
          font-size: 14px;
        }
        
        .entanglement-info {
          background: rgba(0,0,0,0.3);
          border-radius: 8px;
          padding: 12px;
          margin: 12px 0;
        }
        
        .info-row {
          display: flex;
          justify-content: space-between;
          margin: 6px 0;
        }
        
        .label {
          color: #B0C4DE;
          font-size: 14px;
        }
        
        .value {
          color: #00D4FF;
          font-weight: 600;
          font-size: 14px;
        }
        
        .entanglement-explanation h4 {
          margin: 16px 0 8px 0;
          color: #00D4FF;
          font-size: 16px;
        }
        
        .entanglement-explanation ul {
          margin: 0;
          padding-left: 20px;
        }
        
        .entanglement-explanation li {
          margin: 4px 0;
          color: #B0C4DE;
          font-size: 13px;
        }
        
        .farcaster-actions {
          margin-top: 16px;
          text-align: center;
        }
        
        .share-entanglement {
          background: linear-gradient(135deg, #8B5CF6, #06B6D4);
          color: white;
          border: none;
          border-radius: 12px;
          padding: 12px 24px;
          font-size: 14px;
          font-weight: 600;
          cursor: pointer;
          transition: all 0.3s ease;
        }
        
        .share-entanglement:hover {
          transform: translateY(-2px);
          box-shadow: 0 8px 25px rgba(139,92,246,0.4);
        }
      `}</style>
    </div>
  );
};