// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

import "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.9.0/contracts/token/ERC721/ERC721.sol";
import "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.9.0/contracts/token/common/ERC2981.sol";
import "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.9.0/contracts/access/Ownable.sol";
import "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.9.0/contracts/utils/Strings.sol"; 

/**
 * @title Mfer-0-Base with Collaborative Entanglement System
 * @notice Smart gallery-compatible NFT contract with creator-friendly pricing model and revolutionary circular entanglement
 * 
 * MINTING FLOWS:
 * 1. creatorMint() → Artist mints FREE (no ETH, only gas)
 * 2. mintForWithEthFromGallery() + to==artist → Artist's ETH is refunded (generous)
 * 3. mintForWithEthFromGallery() + to≠artist → Gallery receives ETH commission
 * 
 * ENTANGLEMENT SYSTEM:
 * - Each mint generates entanglement data for the NEXT mint in sequence
 * - Circular system: Mint #1000 generates entanglement for Mint #1
 * - Deterministic hash collision using tx.origin + block data
 * - Collaborative gifting: Each minter creates magic for the next person
 * 
 * Storage layout: mapping(string => bool) mintedWithPaymentId ✅
 * Interface: mintForWithEthFromGallery(address,string) payable ✅
 * MaxTotalSupply: 1000 ERC-721 tokens ✅
 * Token ID: Starts from 1 ✅
 */
contract MferBk0Base is ERC721, ERC2981, Ownable {
    using Strings for uint256;

    uint256 private _tokenIdCounter = 1; // ✅ STARTS FROM 1
    string private _baseTokenURI; // ✅ SET VIA CONSTRUCTOR ONLY
    address public gallery;
    address public artist;
    uint96 public royaltyPercentage;
    
    // ✨ CRITICAL: maxTotalSupply for BaseScan recognition
    // This MUST be public for scanners to detect the collection size
    uint256 public maxTotalSupply = 1000; // ✅ BASESCAN WILL RECOGNIZE THIS
    
    // Storage layout: string-based paymentId mapping
    mapping(string => bool) public mintedWithPaymentId;
    
    // 🔮 ENTANGLEMENT SYSTEM: Collaborative circular gifting
    struct EntangledReference {
        uint256 ethMferId;      // Original Ethereum Mfer ID that will be entangled
        bytes32 txHash;         // Transaction hash that generated this entanglement
        uint256 blockNumber;    // Block number for additional entropy
        address generator;      // Who generated this entanglement (the previous minter)
    }
    
    // Each token gets entanglement data generated by the PREVIOUS mint
    // Mint #N generates entanglement for Mint #N+1 (circular: #1000 → #1)
    mapping(uint256 => EntangledReference) public nextMintEntanglement;
    
    // Optional: Track which ethMferId each token is entangled with (for easy lookup)
    mapping(uint256 => uint256) public tokenEntanglement;
    
    event MintedFor(address indexed to, uint256 indexed tokenId, string paymentId);
    event ArtistMinted(address indexed artist, uint256 tokenId, string paymentId);
    event GalleryUpdated(address indexed newGallery);
    event ArtistUpdated(address indexed newArtist);
    event RoyaltyUpdated(uint96 percentage);
    
    // 🔮 ENTANGLEMENT EVENTS
    event EntanglementGenerated(
        uint256 indexed forTokenId,
        uint256 ethMferId,
        bytes32 txHash,
        uint256 blockNumber,
        address indexed generator
    );
    
    /**
     * @dev Constructor
     * @param name_ Contract name: "Mfer-0-Base" ✅
     * @param symbol_ Contract symbol: "MFR0BASE" 
     * @param baseURI_ Metadata URI: "ipfs://bafybeihwtlwxbgnzfjsamyr7uyrgi3bt3osv72vv6muesrq7mnvbrtawcq/"
     * @param initialOwner_ Initial owner (artist): 0xbcd980d37293CBee62Bf5f93a26a0B744C18964D
     */
    constructor(
        string memory name_,
        string memory symbol_,
        string memory baseURI_,
        address initialOwner_
    ) ERC721(name_, symbol_) Ownable() {
        require(initialOwner_ != address(0), "Invalid owner");
        require(bytes(baseURI_).length > 0, "BaseURI required");
        require(bytes(baseURI_)[bytes(baseURI_).length - 1] == '/', "BaseURI must end with /");
        
        _baseTokenURI = baseURI_;
        gallery = initialOwner_;
        artist = initialOwner_;
        royaltyPercentage = 500; // 5% default
        
        // Set default royalty: 5% to artist
        _setDefaultRoyalty(initialOwner_, 500);
    }
    
    modifier onlyGallery() {
        require(msg.sender == gallery, "Only gallery");
        _;
    }
    
    modifier onlyArtist() {
        require(msg.sender == artist, "Only artist");
        _;
    }

    // --- ENTANGLEMENT SYSTEM ---
    
    /**
     * @dev Generate entanglement data for the next mint (collaborative gifting)
     * Called automatically during each mint to create magic for the next person
     */
    function _generateEntanglementForNext(uint256 currentTokenId, address minter) internal {
        // Calculate next token ID (circular: 1000 → 1)
        uint256 nextTokenId = currentTokenId == maxTotalSupply ? 1 : currentTokenId + 1;
        
        // Generate deterministic hash using multiple entropy sources
        bytes32 entropyHash = keccak256(abi.encodePacked(
            tx.origin,           // Transaction originator
            block.timestamp,     // Block timestamp
            block.number,        // Block number
            block.prevrandao,    // Random number from beacon chain (better entropy!)
            minter,             // Minter address
            currentTokenId      // Current token ID
        ));
        
        // Calculate ethMferId using hash collision method (0-9999 range)
        uint256 ethMferId = uint256(entropyHash) % 10000;
        
        // Store entanglement data for next mint
        nextMintEntanglement[nextTokenId] = EntangledReference({
            ethMferId: ethMferId,
            txHash: bytes32(block.number), // Use block number as pseudo-hash for now
            blockNumber: block.number,
            generator: minter
        });
        
        emit EntanglementGenerated(nextTokenId, ethMferId, bytes32(block.number), block.number, minter);
    }
    
    /**
     * @dev Apply entanglement to current mint (use data generated by previous minter)
     */
    function _applyEntanglement(uint256 tokenId) internal {
        EntangledReference memory entanglement = nextMintEntanglement[tokenId];
        
        // If entanglement exists for this token, record it
        if (entanglement.ethMferId > 0) {
            tokenEntanglement[tokenId] = entanglement.ethMferId;
        }
    }

    // --- Artist Minting (FREE) ---
    
    /**
     * @dev Artist mints for free (only gas cost) + generates entanglement
     */
    function creatorMint(string calldata paymentId) external onlyArtist {
        require(bytes(paymentId).length > 0, "Invalid paymentId");
        require(!mintedWithPaymentId[paymentId], "Used");
        
        mintedWithPaymentId[paymentId] = true;
        uint256 tokenId = _tokenIdCounter++;
        require(tokenId <= maxTotalSupply, "Max supply reached");
        
        // 🔮 Apply entanglement from previous mint
        _applyEntanglement(tokenId);
        
        // Mint the token
        _safeMint(artist, tokenId);
        
        // 🔮 Generate entanglement for next mint (collaborative gifting)
        _generateEntanglementForNext(tokenId, artist);
        
        emit ArtistMinted(artist, tokenId, paymentId);
    }

    // --- Gallery Minting (ETH PAYMENT) ---
    
    /**
     * @dev Gallery mints with ETH payment (via KinGallery) + entanglement system
     * If to == artist: refund ETH (generous model)
     * If to != artist: gallery keeps ETH commission
     */
    function mintForWithEthFromGallery(address to, string calldata paymentId) external payable onlyGallery {
        require(to != address(0), "Invalid to");
        require(bytes(paymentId).length > 0, "Invalid paymentId");
        require(!mintedWithPaymentId[paymentId], "Used");
        
        mintedWithPaymentId[paymentId] = true;
        uint256 tokenId = _tokenIdCounter++;
        require(tokenId <= maxTotalSupply, "Max supply reached");
        
        // 🔮 Apply entanglement from previous mint
        _applyEntanglement(tokenId);
        
        // Mint the token
        _safeMint(to, tokenId);
        
        // 🔮 Generate entanglement for next mint (collaborative gifting)
        _generateEntanglementForNext(tokenId, to);
        
        // Handle payment (generous model for artist)
        if (to == artist && msg.value > 0) {
            (bool success, ) = payable(to).call{value: msg.value}("");
            require(success, "Refund failed");
        } else if (msg.value > 0) {
            // Normal flow: gallery keeps the commission
            (bool success, ) = payable(gallery).call{value: msg.value}("");
            require(success, "Transfer failed");
        }
        
        emit MintedFor(to, tokenId, paymentId);
    }

    // --- ENTANGLEMENT VIEW FUNCTIONS ---
    
    /**
     * @dev Get entanglement data that was generated for a specific token
     * @param tokenId Token ID to query entanglement for
     * @return EntangledReference struct with ethMferId, txHash, blockNumber, generator
     */
    function getNextMintEntanglement(uint256 tokenId) external view returns (EntangledReference memory) {
        return nextMintEntanglement[tokenId];
    }
    
    /**
     * @dev Get which ethMferId a token is entangled with
     * @param tokenId Token ID to query
     * @return ethMferId The Ethereum Mfer ID this token is entangled with
     */
    function getTokenEntanglement(uint256 tokenId) external view returns (uint256) {
        return tokenEntanglement[tokenId];
    }
    
    /**
     * @dev Check if entanglement exists for a token
     * @param tokenId Token ID to check
     * @return bool True if entanglement data exists
     */
    function hasEntanglement(uint256 tokenId) external view returns (bool) {
        return nextMintEntanglement[tokenId].ethMferId > 0;
    }

    // --- Admin Functions ---
    
    function setGallery(address _gallery) external onlyOwner {
        require(_gallery != address(0), "Invalid gallery");
        gallery = _gallery;
        emit GalleryUpdated(_gallery);
    }

    function setArtist(address _artist) external onlyOwner {
        require(_artist != address(0), "Invalid artist");
        artist = _artist;
        emit ArtistUpdated(_artist);
    }

    function setRoyalty(uint96 _percentage) external onlyOwner {
        require(_percentage <= 10000, "Royalty too high");
        royaltyPercentage = _percentage;
        _setDefaultRoyalty(artist, _percentage);
        emit RoyaltyUpdated(_percentage);
    }

    function setMaxSupply(uint256 _maxSupply) external onlyOwner {
        require(_maxSupply >= _tokenIdCounter - 1, "Cannot reduce below minted count");
        maxTotalSupply = _maxSupply;
    }

    function setBaseURI(string memory baseURI_) external onlyOwner {
        require(bytes(baseURI_)[bytes(baseURI_).length - 1] == '/', "BaseURI must end with /");
        _baseTokenURI = baseURI_;
    }

    // --- Metadata ---
    
    function _baseURI() internal view override returns (string memory) {
        return _baseTokenURI;
    }

    /// @notice tokenURI returns baseURI + tokenId + ".json"
    function tokenURI(uint256 tokenId) public view override returns (string memory) {
        require(_exists(tokenId), "ERC721Metadata: URI query for nonexistent token");
        string memory baseURI = _baseURI();
        return bytes(baseURI).length > 0 ? string(abi.encodePacked(baseURI, tokenId.toString(), ".json")) : "";
    }

    function supportsInterface(bytes4 interfaceId) public view override(ERC721, ERC2981) returns (bool) {
        return super.supportsInterface(interfaceId);
    }

    // --- Utility & BaseScan Compatibility ---
    
    /**
     * @dev Total number of tokens currently minted (for BaseScan recognition)
     * This is the standard ERC721 totalSupply interface that scanners expect
     */
    function totalSupply() external view returns (uint256) {
        return _tokenIdCounter - 1;
    }
    
    /**
     * @dev Total number of tokens minted (alias for compatibility)
     */
    function totalMinted() external view returns (uint256) {
        return _tokenIdCounter - 1;
    }

    /**
     * @dev Remaining supply before reaching maxTotalSupply
     */
    function remainingSupply() external view returns (uint256) {
        return maxTotalSupply - (_tokenIdCounter - 1);
    }
    
    /**
     * @dev Check if token exists (for BaseScan token validation)
     */
    function exists(uint256 tokenId) external view returns (bool) {
        return _exists(tokenId);
    }
    
    /**
     * @dev Maximum possible supply (for scanner compatibility)
     * Some scanners look for this specific function name
     */
    function maxSupply() external view returns (uint256) {
        return maxTotalSupply;
    }
    
    /**
     * @dev Check if this collection has a fixed maximum supply
     * Returns true since we have a hard cap of 1000 tokens
     */
    function hasMaxSupply() external pure returns (bool) {
        return true;
    }

    receive() external payable {}
}